In [1]:
import os, sys

currentdir = os.getcwd()
parentdir = os.path.dirname(currentdir)
sys.path.append(parentdir+'/pybary')

In [2]:
from numpy import power, array, exp, zeros
from numpy.random import normal
from numpy.linalg import norm
from functools import reduce

from pybary import bary_batch, bary_recursive

In [11]:
# Oracle function
oracle = lambda x: norm(x)

# Hyperparameters
nu = 1
sigma = 0.1
zeta = 0
lambda_ = 1

In [4]:
xs_test = array([[0, 0], [1, 1]])

bexp_fun = lambda x: exp(-nu*oracle(x))

den = bexp_fun(xs_test[0]) + bexp_fun(xs_test[1])
num = xs_test[0]*bexp_fun(xs_test[0]) + xs_test[1]*bexp_fun(xs_test[1])

bexp_fun = lambda x: exp(-nu*oracle(x))
oracle_eval = list(map(bexp_fun, xs_test))

print('Evaluations : '+str(oracle_eval))
print('Numerator   : '+str(num))
print('Denominator : '+str(den))
print('Barycenter  : '+str(num/den))

Evaluations : [1.0, 0.2431167344342142]
Numerator   : [0.24311673 0.24311673]
Denominator : 1.2431167344342142
Barycenter  : [0.19557032 0.19557032]


In [5]:
xs = xs_test

n = len(xs[0])
size_x = (n, 1)

prod_func = lambda elems: elems[0]*elems[1]
sum_func = lambda acc, a: acc + a

num = reduce(
    sum_func, 
    map(prod_func, zip(map(bexp_fun, xs), xs)), 
    zeros(size_x).T
)

den = reduce(sum_func, map(bexp_fun, xs), 0)

print(num)
print(den)
print(num/den)

[[0.24311673 0.24311673]]
1.2431167344342142
[[0.19557032 0.19557032]]


In [7]:
print(bary_batch(oracle, xs_test, nu))

[[0.19557032 0.19557032]]


In [9]:
# Batch setup

# Points for batch barycenter version
mu_x = 0
sigma_x = 1
size_batch = [1000, 2]

xs = normal(mu_x, sigma_x, size_batch)

# Batch run
xhat_batch = bary_batch(oracle, xs, nu)

# Results
print(xhat_batch)

[[-0.01302158 -0.00317233]]


In [10]:
# Recursive setup

# Initial point
x0 = array([0, 0])

# Iteration cardinality
iterations = 1000

# Recursive run
xhat_recursive = bary_recursive(oracle, x0, nu, sigma, zeta, lambda_, iterations)

print(xhat_recursive)


[[-0.01861115 -0.12754478]]
